[default]
addreess = "0.0.0.0"
port = 8080

[default.tls]
key = "./certs/private-key.pem"
certs = "./certs/certificate-chain.pem"

[release]
address = "0.0.0.0"
port = 8080
ip_header = false
ident = "FunLe"