import { AbsoluteCenter } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";


export default function EditTest() {

    const router = useRouter();
    const id = router.query.id;

    return (
        <>
            <Head>
                <title>Edit Test</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <AbsoluteCenter>
                <h1>Edit Test with ID: {id}</h1>
            </AbsoluteCenter>
        </>
    )
}