import React from "react";
import Head from "next/head";

export default function Tests() {
    return (
        <>
            <Head>
                <title>tests</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <main>
                <h1>tests</h1>
            </main>
        </>
    );
}
