import React from "react";
import Head from "next/head";
import { Box } from "@chakra-ui/react";
import TestCard from "../components/card";

export default function Tests() {
    return (
        <>
            <Head>
                <title>tests</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <Box>
                <TestCard id="test" text="test" type="action" onClick={() => {}} onDelete={() => {}}/>
            </Box>
        </>
    );
}
