import React from "react";
import Head from "next/head";

export default function Tutorilas() {
    return (
        <>
            <Head>
                <title>Tutorilas</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <main>
                <h1>Tutorilas</h1>
            </main>
        </>
    );
}
