// Next js hello world


import React from "react";
import Head from "next/head";

export default function Cources() {
    return (
        <>
            <Head>
                <title>Cources</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <main>
                <h1>Cources</h1>
            </main>
        </>
    );
}
