import {
    AbsoluteCenter,
    Button,
    Center,
    HStack,
    Input,
    Menu,
    MenuOptionGroup,
    NumberInput,
    NumberInputField,
    Radio,
    RadioGroup,
    Switch,
    Text,
} from "@chakra-ui/react";
import Head from "next/head";
import { useCallback, useEffect, useState } from "react";
import { FaPlus } from "react-icons/fa";
import AddOptionButton from "../../components/addOptionButton";
import BottomFloatingButton from "../../components/bottomFloatingButton";
import OptionCard from "../../components/option";

interface ActionsOptionsChoice {
    text: string;
    isCorrect: boolean;
}

interface ActionsOptionsAction {
    text: string;
}

export default function CreateNewTest() {
    const [testType, setTestType] = useState<"choice" | "action">("choice"); // "choice" or "action"

    const [actions, setActions] = useState<
        ActionsOptionsChoice[] | ActionsOptionsAction[]
    >([]);
    const [question, setQuestion] = useState<string>("");
    const [themeOfTest, setThemeOfTest] = useState<string>("");
    const [levelOfTest, setLevelOfTest] = useState<number>();

    let apiAnswers: any = [];
    let correctAnswers: string = "";
    for (let i = 0; i < actions.length; i++) {
        apiAnswers.push(actions[i].text);
        if (testType === "choice") {
            if ((actions[i] as ActionsOptionsChoice).isCorrect) {
                correctAnswers = actions[i].text;
            }
        }
    }

    const handleCreateTestButton = () => {
        if (testType === "choice") {
            let apiObject = {
                theme: themeOfTest,
                text_of_question: question,
                answers: apiAnswers,
                correct_answers: correctAnswers,
                level: levelOfTest,
            };
            console.log(apiObject); // TODO: send to API
        } else {
            let apiObject = {
                theme: themeOfTest,
                example: question,
                actions: actions,
                // get last action from actions list
                answer: actions[actions.length - 1].text,
                level: levelOfTest,
            };
            console.log(apiObject); // TODO: send to API
        }
    };

    const onTestTypeChanged = (value: string) => {
        setTestType(value as "choice" | "action");
        setActions([]);
    };

    const deleteOption = (index: number) => {
        // remove object from actions list. index is the index of the object to be removed
        for (let i = 0; i < actions.length; i++) {
            if (i === index) {
                const temp = [...actions];
                temp.splice(index, 1);
                setActions(temp);
            }
        }
    };

    useEffect(() => {
        console.log(actions);
    }, [actions]);

    return (
        <>
            <Head>
                <title>Create New Test</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <AbsoluteCenter w={"400px"}>
                {/* Text of question */}
                <Input
                    value={question}
                    onChange={(e) => setQuestion(e.target.value)}
                    border={"1px solid black"}
                    placeholder={"Question"}
                    focusBorderColor={"orange.500"}
                    _hover={{
                        borderColor: "orange.400",
                        bgColor: "orange.50",
                        _placeholder: { color: "blackAlpha.900" },
                    }}
                />
                <Input
                    marginTop={"10px"}
                    marginBottom={"10px"}
                    value={themeOfTest}
                    onChange={(e) => setThemeOfTest(e.target.value)}
                    border={"1px solid black"}
                    placeholder={"Theme of test"}
                    focusBorderColor={"orange.500"}
                    _hover={{
                        borderColor: "orange.400",
                        bgColor: "orange.50",
                        _placeholder: { color: "blackAlpha.900" },
                    }}
                />
                <NumberInput focusBorderColor="orange.500">
                    <NumberInputField
                        placeholder="Level of question"
                        value={levelOfTest}
                        onChange={(e) => setLevelOfTest(Number(e.target.value))}
                        border={"1px solid black"}
                        _hover={{
                            borderColor: "orange.400",
                            bgColor: "orange.50",
                            _placeholder: { color: "blackAlpha.900" },
                        }}
                    />
                </NumberInput>
                {/* Text type switch */}
                <Center>
                    <RadioGroup
                        onChange={onTestTypeChanged}
                        value={testType}
                        colorScheme="orange"
                    >
                        <HStack justifyContent={"space-around"}>
                            <Radio value="choice">Choice</Radio>
                            <Radio value="action">Action</Radio>
                        </HStack>
                    </RadioGroup>
                </Center>
                {
                    // if emit("update_actions") is called, this will be updated
                    actions &&
                        actions.map((action, index) => {
                            return (
                                <OptionCard
                                    key={index.toString()}
                                    data={action}
                                    type={testType}
                                    index={index}
                                    onEdit={(data) => {
                                        const temp = [...actions];
                                        temp[index] = data;
                                        setActions(temp);
                                    }}
                                    onDelete={deleteOption}
                                />
                            );
                        })
                }
                <AddOptionButton
                    _type={testType}
                    onClick={() => {
                        // TODO: add new option to actions list
                        if (testType === "choice") {
                            setActions([
                                ...actions,
                                {
                                    text: "",
                                    isCorrect: false,
                                },
                            ]);
                        } else {
                            setActions([
                                ...actions,
                                {
                                    text: "",
                                },
                            ]);
                        }
                    }}
                />
            </AbsoluteCenter>
            <BottomFloatingButton
                text="Create"
                icon={<FaPlus />}
                onClick={() => {
                    handleCreateTestButton();
                }}
            />
        </>
    );
}
