import { AbsoluteCenter } from "@chakra-ui/react";
import Head from "next/head";


export default function CreateNewTest() {
    return (
        <>
            <Head>
                <title>Create New Test</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <AbsoluteCenter>
                <h1>Create New Test</h1>
            </AbsoluteCenter>
        </>
    );
}